### ISSUE TITLE
长消息接受被分割

### ISSUE THREAD

**Issue by SitaNya** [YuQWorks/YuQ-Mirai#17]
在接受长消息时，不知是mirai还是QQ层对消息做了分割，如图所示

`.st 青-力量85str85敏捷75dex75意志60pow60体质75con75外貌20app20教育60edu60体型40siz40智力60灵感60int60san60san值60理智60理智值60幸运75运气75mp12魔法12hp11体力11会计5人类学1估价5考古学1魅惑50攀爬60计算机5计算机使用5电脑5信用0信誉0信用评级0克苏鲁0克苏鲁神话0cm0乔装60闪避82汽车20驾驶20汽车驾驶20电气维修10电子学1话术5斗殴80手枪60急救80历史5恐吓15跳跃20母语60法律5图书馆20图书馆使用20聆听75开锁1撬锁1锁匠1机械维修10医学55博物学10自然学10领航10导航10神秘学5重型操作1重型机械1操作重型机械1说服75精神分析1心理学10骑术60妙手10侦查20潜行80生存10游泳70投掷20追踪70驯兽70潜水70爆破1读唇1催眠1炮术1`

这条消息在mirai段接受时为

`2020/08/12 22:48:03 [0m2020-08-12 22:48:03 V/Bot 2478573305: [塔骰6版测试(xxxxx)] 七月(xxxxxx) -> [mirai:source:4928,487660255].st 青-力量85str85敏捷75dex75意志60pow60体质75con75外貌20app20教育60edu60体型40siz40智力60灵感60int60san60san值60理智60理智值60幸运75运气75mp12魔法12hp11体力11会计5人类学1估价5考古学1魅惑50攀爬60计算机5计算机使用5电脑5信用0信誉0信用评级0克苏鲁0克苏鲁神话0cm0乔装60闪避82汽车20驾驶20汽车驾驶20电气维修10电子学1话术5斗殴80手枪60急救80历史5恐吓15跳跃20母语60法律5图书馆20图书馆使用20聆听75开锁1撬锁1锁匠1机械维修10医学55博物学10

2020/08/12 22:48:03 [0m2020-08-12 22:48:03 V/Bot 2478573305: [塔骰6版测试(xxxxxx)] 七月(xxxxx) -> [mirai:source:4929,425358424]自然学10领航10导航10神秘学5重型操作1重型机械1操作重型机械1说服75精神分析1心理学10骑术60妙手10侦查20潜行80生存10游泳70投掷20追踪70驯兽70潜水70爆破1读唇1催眠1炮术1
`

**Comment by IceCream-Open** [comment]
请提供发送消息人使用的 QQ 平台及版本。
如：Windows QQ 9.3.6

**Comment by coqiyue** [comment]
发送消息的人使用的版本是[QQHD V5.8.8.3]
![IMG_20200819_200037](https://user-images.githubusercontent.com/68550017/90632245-b0d47580-e256-11ea-82eb-aef34f75d1a2.jpg)

**Comment by IceCream-Open** [comment]
当前版本：0.0.6.9 已经尝试解决该问题，如果依旧产生此问题，请重复打开此 issue
