### ISSUE TITLE
改头衔啊改头衔，戳一戳啊戳一戳

### ISSUE THREAD

**Issue by coide-SaltedFish** [YuQWorks/YuQ-Mirai#27]
希望新增改头衔功能和实装戳一戳功能

**Comment by lcx1969001** [comment]
可以将YuQ强制类型转换成Mirai的Bot对象，用Bot对象设置头衔
        MiraiBot miraiBot = (MiraiBot) yuq;
        Bot bot = miraiBot.getBot();

**Comment by IceCream-Open** [comment]
改头衔 #25 
戳一戳已经提供相关 API。
Friend 与 Member 中提供了 click 方法用于实现 手机QQ 中双击头像的 戳一戳 动作。
