### ISSUE TITLE
请求被踢出与被禁言监听

### ISSUE THREAD

**Issue by SitaNya** [YuQWorks/YuQ-Mirai#7]
如题，mirai直到结束也没能解决监听被踢出和被禁言的问题，我最后一次了解进展位于

T出时会触发OnlinePush.Trans MsgType为34 SubType为0x03
可参考 https://github.com/Mrs4s/MiraiGo/blob/c6b4c61122f97dbbd0545912e1c45959b146a0c5/client/decoders.go#L425

如果可能的话希望修复，感谢

**Comment by IceCream-Open** [comment]
关联 mirai issue https://github.com/mamoe/mirai/issues/358

**Comment by IceCream-Open** [comment]
当前版本：0.0.6.9 已经尝试解决该问题，如果依旧产生此问题，请重复打开此 issue
